language: dart
dart:
 - dev

before_install:
  - chmod +x build.sh

stages:
  - setup
  - build
  - deploy

jobs:
  include:
    - stage: build
      script: ./build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master