language: dart
dart:
 - dev

stages:
  - setup
  - build
  - deploy
jobs:
  include:
    - stage: build
      script: ./build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master