language: dart
dart:
 - dev

jobs:
  include:
    - stage: build
      script: webdev build


deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master