language: dart
dart:
 - dev

before_install:
  - pub global activate webdev
  #- pub global activate peanut


jobs:
  include:
    - stage: build
      script: webdev build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: dart.kwatra.me
  local-dir: build
  on:
    branch: master
